export const MenuItems = [
  {
    title: 'MENU',
    items: [
      {
        icon: '/home.png',
        label: 'Home',
        href: '/dashboard',
      },

      {
        icon: '/book.png',
        label: 'Booking',
        href: '/booking',
      },
      {
        icon: '/calendar.png',
        label: 'Calendar',
        href: '/calendar',
      },
    ],
  },
  {
    title: 'PANEL',
    items: [
      {
        icon: '/profile.png',
        label: 'Profile',
        href: '/profile',
      },
      {
        icon: '/employee.png',
        label: 'Employee',
        href: '/employee',
      },

      {
        icon: '/logout.png',
        label: 'Logout',
        href: '/logout',
      },
    ],
  },
];
// export const eventsData = [
//   {
//     id: 1,
//     client_name: 'Girish Digge',
//     email: 'thegame.girish@gmail.com',
//     phone: 9988776655,
//     phoneAlt: 9999888877,
//     address: '1, Park Avenue, NY',
//     hall: 'Main Hall',
//     event_name: 'Wedding',
//     balance: 12000,
//     amount: 75000,
//     date: '2025-04-04',
//     start_time: '10:00',
//     end_time: '11:00',
//   },
//   {
//     id: 2,
//     client_name: 'Priya Sharma',
//     email: 'priya.sharma@example.com',
//     phone: 9876543210,
//     phoneAlt: 9123456789,
//     address: '15, MG Road, Bangalore',
//     hall: 'Banquet Hall A',
//     event_name: 'Birthday Party',
//     balance: 5000,
//     amount: 40000,
//     date: '2025-05-10',
//     start_time: '18:00',
//     end_time: '22:00',
//   },
//   {
//     id: 3,
//     client_name: 'Amit Patel',
//     email: 'amit.p@sample.net',
//     phone: 9234567890,
//     phoneAlt: null,
//     address: 'Flat 301, Sunshine Apartments, Mumbai',
//     hall: 'Garden View',
//     event_name: 'Anniversary Celebration',
//     balance: 0,
//     amount: 55000,
//     date: '2025-06-15',
//     start_time: '19:00',
//     end_time: '23:00',
//   },
//   {
//     id: 4,
//     client_name: 'Deepa Iyer',
//     email: 'deepa.i@email.org',
//     phone: 9345678901,
//     phoneAlt: 9456789012,
//     address: 'Plot 45, Sector 10, Noida',
//     hall: 'Conference Room 1',
//     event_name: 'Corporate Meeting',
//     balance: 10000,
//     amount: 25000,
//     date: '2025-04-20',
//     start_time: '09:00',
//     end_time: '17:00',
//   },
//   {
//     id: 5,
//     client_name: 'Rajesh Kumar',
//     email: 'rajesh.k@domain.com',
//     phone: 9567890123,
//     phoneAlt: 9678901234,
//     address: 'House No. 12, Green Park, Delhi',
//     hall: 'Main Hall',
//     event_name: 'Wedding Reception',
//     balance: 25000,
//     amount: 90000,
//     date: '2025-07-01',
//     start_time: '18:30',
//     end_time: '23:30',
//   },
//   {
//     id: 6,
//     client_name: 'Sunita Singh',
//     email: 'sunita.singh@mail.co',
//     phone: 9789012345,
//     phoneAlt: null,
//     address: '22, Richmond Town, Bangalore',
//     hall: 'Terrace Lounge',
//     event_name: 'Engagement Party',
//     balance: 7000,
//     amount: 60000,
//     date: '2025-08-12',
//     start_time: '19:00',
//     end_time: '22:30',
//   },
//   {
//     id: 7,
//     client_name: 'Vikram Mehta',
//     email: 'vikram.m@service.io',
//     phone: 9890123456,
//     phoneAlt: 9901234567,
//     address: 'A-5, Sea View Apts, Chennai',
//     hall: 'Banquet Hall B',
//     event_name: 'Product Launch',
//     balance: 15000,
//     amount: 50000,
//     date: '2025-05-25',
//     start_time: '11:00',
//     end_time: '14:00',
//   },
//   {
//     id: 8,
//     client_name: 'Anjali Rao',
//     email: 'anjali.rao@email.com',
//     phone: 9012345678,
//     phoneAlt: 9123456780,
//     address: '7th Floor, Tech Tower, Hyderabad',
//     hall: 'Conference Room 2',
//     event_name: 'Seminar',
//     balance: 3000,
//     amount: 20000,
//     date: '2025-06-05',
//     start_time: '10:00',
//     end_time: '16:00',
//   },
//   {
//     id: 9,
//     client_name: 'Sandeep Reddy',
//     email: 'sandeep.r@sample.org',
//     phone: 9123456789,
//     phoneAlt: null,
//     address: 'Villa 8, Gachibowli, Hyderabad',
//     hall: 'Poolside Area',
//     event_name: 'Birthday Bash',
//     balance: 10000,
//     amount: 45000,
//     date: '2025-09-20',
//     start_time: '17:00',
//     end_time: '21:00',
//   },
//   {
//     id: 10,
//     client_name: 'Meera Desai',
//     email: 'meera.d@email.net',
//     phone: 9234567800,
//     phoneAlt: 9345678001,
//     address: 'Block C, Flat 10, Koregaon Park, Pune',
//     hall: 'Main Hall',
//     event_name: 'Charity Gala',
//     balance: 50000,
//     amount: 150000,
//     date: '2025-10-18',
//     start_time: '19:30',
//     end_time: '00:00',
//   },
//   // {
//   //   id: 11,
//   //   client_name: 'Arjun Nair',
//   //   email: 'arjun.nair@provider.com',
//   //   phone: 9456789011,
//   //   phoneAlt: 9567890112,
//   //   address: '405, Lakeview Residency, Kolkata',
//   //   hall: 'Garden View',
//   //   event_name: 'Wedding Anniversary',
//   //   balance: 8000,
//   //   amount: 65000,
//   //   date: '2025-11-22',
//   //   start_time: '20:00',
//   //   end_time: '23:59',
//   // },
// ];

export const announcementsData = [
  {
    id: 1,
    title: 'About 4A Math Test',
    class: '4A',
    date: '2025-04-04',
  },
];

export type BookingEvent = {
  title: string;
  hall: 'mainHall' | 'secondHall';
  start: Date;
  end: Date;
};
export const calendarEvents: BookingEvent[] = [
  {
    title: 'Wedding',
    hall: 'mainHall',
    start: new Date(2025, 3, 15, 8, 0),
    end: new Date(2025, 3, 15, 12, 45),
  },
  {
    title: 'Farewell',
    hall: 'secondHall',
    start: new Date(2025, 3, 15, 18, 0),
    end: new Date(2025, 3, 15, 22, 45),
  },
];
